# Generated by Django 5.1 on 2024-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='profile')),
                ('name', models.CharField(max_length=200)),
                ('posstion', models.CharField(max_length=200)),
                ('disc', models.TextField(max_length=2000)),
            ],
        ),
    ]
