# Generated by Django 5.1 on 2024-08-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='disc',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='posstion',
            new_name='postion',
        ),
    ]
