# Generated by Django 5.1 on 2024-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=100)),
                ('employees', models.IntegerField()),
                ('HOD', models.CharField(max_length=100)),
                ('depPhone', models.IntegerField(max_length=10)),
                ('depImail', models.EmailField(max_length=254)),
            ],
        ),
    ]
