# Generated by Django 5.1 on 2024-08-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_resignetion_employee_designetion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employees',
        ),
    ]
