# Generated by Django 5.1 on 2024-08-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_employee_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='designetion',
            new_name='designation',
        ),
    ]
