# Generated by Django 5.1 on 2024-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_rename_designetion_employees_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('studentRollNo', models.IntegerField(max_length=20)),
                ('collegeId', models.IntegerField(max_length=200)),
                ('collegeName', models.CharField(max_length=300)),
                ('subject1Marks', models.IntegerField(max_length=3)),
                ('subject2Marks', models.IntegerField(max_length=3)),
                ('subject3Marks', models.IntegerField(max_length=3)),
                ('subject4Marks', models.IntegerField(max_length=3)),
                ('subject5Marks', models.IntegerField(max_length=3)),
                ('totalMarks', models.IntegerField(max_length=6)),
                ('persentage', models.IntegerField(max_length=6)),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
    ]
