# Generated by Django 5.1 on 2024-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('studentRollNo', models.IntegerField()),
                ('collegeId', models.IntegerField()),
                ('collegeName', models.CharField(max_length=300)),
                ('subject1Marks', models.IntegerField()),
                ('subject2Marks', models.IntegerField()),
                ('subject3Marks', models.IntegerField()),
                ('subject4Marks', models.IntegerField()),
                ('subject5Marks', models.IntegerField()),
                ('totalMarks', models.IntegerField()),
                ('persentage', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='department',
            name='depPhone',
            field=models.IntegerField(),
        ),
    ]
