# Generated by Django 5.1 on 2024-08-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_students_delete_student_alter_department_depphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
