# Generated by Django 5.1 on 2024-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depPhone',
            field=models.CharField(max_length=15),
        ),
    ]
